import { getDayNumber, getTodayString } from "./supabase";

export const MORNING_QUOTES = [
  "LOOK IN THE MIRROR. THAT'S YOUR OPPONENT. EVERY REP, EVERY MEAL, EVERY SECOND COUNTS.",
  "GRADUATION PHOTOS ARE FOREVER. YOUR FAMILY. YOUR FRIENDS. YOUR FUTURE SELF. MAKE SURE THE MAN IN THE PHOTO EARNED IT.",
  "COMFORT IS WHERE AMBITION GOES TO DIE. THE PAIN IS TEMPORARY. THAT JAWLINE IS PERMANENT.",
  "NOBODY CARES ABOUT YOUR EXCUSES. THE SCALE DOESN'T LIE. THE MIRROR DOESN'T LIE. GET UP.",
  "YOU'RE NOT DIETING — YOU'RE GOING TO WAR WITH MEDIOCRITY. EVERY GRAM OF SODIUM IS SABOTAGE.",
  "DISCIPLINE IS DOING IT WHEN YOU DON'T FEEL LIKE IT. THAT'S THE WHOLE GAME.",
  "YOUR COMPETITION ISN'T RESTING. WHILE YOU SLEEP IN, THEY'RE GRINDING. WAKE UP.",
  "PAIN IS WEAKNESS LEAVING THE BODY. EMBRACE IT OR STAY SOFT.",
  "33 DAYS. THAT'S ALL YOU GET. WASTE ONE AND YOU'LL NEVER GET IT BACK.",
  "THE BODY YOU WANT IS ON THE OTHER SIDE OF THE WORK YOU'RE AVOIDING.",
  "EVERY MEAL IS A CHOICE. EVERY CHOICE IS A VOTE FOR WHO YOU BECOME ON APRIL 22.",
  "YOU DIDN'T COME THIS FAR TO ONLY COME THIS FAR. FINISH WHAT YOU STARTED.",
  "AVERAGE PEOPLE QUIT WHEN IT GETS HARD. YOU'RE NOT AVERAGE. PROVE IT TODAY.",
  "YOUR BRAIN IS BEGGING YOU TO QUIT. THAT'S HOW YOU KNOW IT'S WORKING.",
  "THE DIFFERENCE BETWEEN WHO YOU ARE AND WHO YOU WANT TO BE IS WHAT YOU DO TODAY.",
];

export const EVENING_QUOTES = [
  "THE DAY ISN'T OVER. YOUR TASKS ARE STILL WAITING. NO EXCUSES.",
  "YOU'RE ABOUT TO GO TO SLEEP WITH UNFINISHED BUSINESS. IS THAT WHO YOU ARE?",
  "EVERY UNCHECKED TASK IS A BROKEN PROMISE TO YOURSELF. FIX IT BEFORE MIDNIGHT.",
  "YOU HAD 24 HOURS. YOU'RE RUNNING OUT. GET IT DONE OR LIVE WITH THE REGRET.",
  "TOMORROW'S VERSION OF YOU IS WATCHING. DON'T LET HIM DOWN TONIGHT.",
  "THE CLOCK IS TICKING. THOSE TASKS WON'T COMPLETE THEMSELVES. MOVE.",
  "SLEEP IS EARNED, NOT GIVEN. FINISH YOUR TASKS FIRST.",
  "YOU STILL HAVE TIME. BUT NOT MUCH. EVERY MINUTE YOU WASTE IS A MINUTE GONE FOREVER.",
  "INCOMPLETE TASKS = INCOMPLETE COMMITMENT. IS THIS THE BEST YOU CAN DO?",
  "DON'T LET TODAY BE THE DAY THAT BREAKS YOUR STREAK. YOU'RE BETTER THAN THAT.",
];

export const STREAK_BREAK_QUOTES = [
  "YOU BROKE THE CHAIN. YOUR FACE WON'T DEBLOAT WITH EXCUSES. GET BACK ON IT TODAY.",
  "STREAK LOST. EVERY MISSED DAY IS A DAY DUY STAYS THE SAME. FIX IT NOW.",
  "YOU HAD MOMENTUM. YOU THREW IT AWAY. THE ONLY WAY OUT IS THROUGH. START AGAIN.",
  "MISSED A DAY? YOUR JAWLINE DOESN'T CARE ABOUT YOUR REASONS. EXECUTE.",
  "THE STREAK IS DEAD. BUT YOU'RE NOT. REBUILD IT. ONE TASK AT A TIME.",
  "YESTERDAY YOU FAILED. TODAY YOU CHOOSE: REPEAT THE FAILURE OR FIGHT BACK.",
  "A BROKEN STREAK IS A SCAR. WEAR IT, LEARN FROM IT, AND NEVER LET IT HAPPEN AGAIN.",
  "YOU LOST A DAY. YOU CAN'T GET IT BACK. BUT YOU CAN MAKE TODAY COUNT DOUBLE.",
  "QUITTERS MISS DAYS. WARRIORS DON'T. WHICH ONE ARE YOU?",
  "THE CHAIN IS BROKEN. EVERY HOUR YOU WASTE MAKES IT HARDER TO RESTART. GO. NOW.",
];

export function getQuoteOfTheDay(pool: string[], date?: string): string {
  const today = date ?? getTodayString();
  const dayNum = getDayNumber(today);
  return pool[dayNum % pool.length];
}
